import uuid
from datetime import datetime
from typing import List, Optional, Any, Dict
from sqlalchemy import String, ForeignKey, DateTime, Boolean, Float
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.database import Base

class AIAgent(Base):
    """
    Supervised autonomous machine learning agent definitions.
    """
    __tablename__ = "ai_agents"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(100), unique=True, nullable=False, index=True)
    description: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="active") # active, inactive
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    model_versions: Mapped[List["ModelVersion"]] = relationship(back_populates="agent")
    chaos_tests: Mapped[List["ChaosTest"]] = relationship(back_populates="target_agent")

class ModelVersion(Base):
    """
    Deployed version hashes and telemetry parameters of active agents.
    """
    __tablename__ = "model_versions"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ai_agents.id", ondelete="CASCADE"), nullable=False, index=True)
    version_string: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    parameters_hash: Mapped[str] = mapped_column(String(100), nullable=False)
    accuracy_benchmark: Mapped[float] = mapped_column(Float, default=0.00)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    deployed_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    hyperparameters: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)
    metrics: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)

    # Relationships
    agent: Mapped[AIAgent] = relationship(back_populates="model_versions")
    predictions: Mapped[List["Prediction"]] = relationship(back_populates="model_version")

class Prediction(Base):
    """
    Decisions generated by individual model pings.
    """
    __tablename__ = "predictions"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    transaction_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("transactions.id", ondelete="CASCADE"), nullable=False, index=True)
    model_version_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("model_versions.id", ondelete="RESTRICT"), nullable=False, index=True)
    
    prediction_output: Mapped[Dict[str, Any]] = mapped_column(JSONB, nullable=False) # raw prediction keys
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    transaction: Mapped["Transaction"] = relationship(back_populates="predictions")
    model_version: Mapped[ModelVersion] = relationship(back_populates="predictions")
    explanations: Mapped[List["Explanation"]] = relationship(back_populates="prediction")

class MLOpsDeployment(Base):
    """
    Active traffic routing rules (Canary splits, Shadow paths, A/B sets) for supervised ML models.
    """
    __tablename__ = "mlops_deployments"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ai_agents.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    deployment_type: Mapped[str] = mapped_column(String(50), default="production", index=True) # production, canary, shadow, ab_testing
    
    active_version_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True)
    canary_version_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True)
    canary_split: Mapped[int] = mapped_column(default=100) # percentage of traffic to Canary (e.g. 10)
    
    shadow_version_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True)
    
    ab_version_a_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True)
    ab_version_b_id: Mapped[Optional[uuid.UUID]] = mapped_column(ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True)
    ab_split: Mapped[int] = mapped_column(default=50) # percentage of traffic to A (e.g. 50)
    
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class MLflowRun(Base):
    """
    Simulated MLflow run logs storing training hyperparams and accuracy evaluation metrics.
    """
    __tablename__ = "mlflow_runs"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ai_agents.id", ondelete="CASCADE"), nullable=False, index=True)
    run_name: Mapped[str] = mapped_column(String(100), nullable=False)
    experiment_id: Mapped[str] = mapped_column(String(100), default="default")
    parameters: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)
    metrics: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)
    status: Mapped[str] = mapped_column(String(50), default="FINISHED")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

class DeploymentHistory(Base):
    """
    Audit log trail recording model promotion, canary splits, and rollback triggers.
    """
    __tablename__ = "deployment_history"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    agent_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("ai_agents.id", ondelete="CASCADE"), nullable=False, index=True)
    action: Mapped[str] = mapped_column(String(100), nullable=False, index=True) # promote, rollback, configure
    details: Mapped[str] = mapped_column(String(500), nullable=False)
    performed_by: Mapped[str] = mapped_column(String(100), default="system")
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

